import { test, expect } from "@playwright/test";
test("context corrections, sections and evidence links", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: /Try a sample question/ }).click();
  await page.getByRole("button", { name: "Start huddle", exact: true }).click();
  await page.getByLabel("Topic", { exact: true }).fill("Clinical trials");
  await page.getByLabel("Intent", { exact: true }).fill("Prepare expert questions");
  await expect(page.getByRole("button", { name: "Evidence", exact: true })).toBeDisabled();
  await page.getByRole("button", { name: "Confirm context" }).click();
  await expect(page.getByRole("heading", { name: "Why this expert?" })).toBeVisible();
  await expect(page.getByText("MD — illustrative qualification", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Request Expert Connection", exact: true }).click();
  await page.getByRole("button", { name: "Brief", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Your brief is not ready yet" })).toBeVisible();
  await page.getByRole("button", { name: "Evidence", exact: true }).click();
  await expect(page.getByRole("heading", { name: /Evidence to explore/ })).toBeVisible();
  await page.getByRole("button", { name: "Expert", exact: true }).click();
  await page.getByRole("button", { name: "Use simulated response" }).click();
  await page.getByRole("button", { name: "Evidence", exact: true }).click();
  await page.getByRole("button", { name: "Expert", exact: true }).click();
  await expect(page.getByLabel("Or type your response")).toHaveValue(/For this sample case/);
  await page.getByRole("button", { name: "Create huddle brief" }).click();
  await expect(page.getByRole("navigation", { name: "Breadcrumb" })).toHaveText(/WorkspaceMy HuddlesHuddle Brief/);
  await expect(page.locator(".takeaways")).toContainText("clinical trials discussion");
  await expect(page.locator(".takeaways")).toContainText("Prepare expert questions");
  await expect(page.locator(".takeaways a")).toHaveCount(3);
  await expect(page.locator(".takeaways a").first()).toHaveAttribute("href", "https://www.cancer.gov/types/breast/hp/breast-treatment-pdq");
  await page.getByRole("button", { name: "Question", exact: true }).click();
  await expect(page.getByLabel("Topic", { exact: true })).toHaveValue("Clinical trials");
  await page.getByLabel("Condition", { exact: true }).fill("Arrhythmia");
  await page.getByLabel("Specialty", { exact: true }).fill("Cardiology");
  await page.getByRole("button", { name: "Confirm context" }).click();
  await expect(page.getByRole("heading", { name: "No expert match", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Brief", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Your brief is not ready yet" })).toBeVisible();
  await page.reload();
  await page.getByRole("button", { name: /Clinical trials Sample case/ }).click();
  await page.getByRole("button", { name: "Question", exact: true }).click();
  await expect(page.getByLabel("Condition", { exact: true })).toHaveValue("Arrhythmia");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
